-- Where's Joe? — seed data (7 Austin cafés + categorized tags)
-- Run this AFTER schema.sql. Inserts the starter café catalogue.
-- NOTE: user-generated data (profiles, posts, saves) is NOT seeded — it
-- comes from real signups. This only populates the café catalogue.

begin;

with seeded (name, address, city, state, country, latitude, longitude, description, website, instagram, phone, cover_photo_url, gallery, verified_by_joe, status, neighborhood, signature_drink, hours, rating, review_count, price_tier) as (
  values
  ('Morning House Coffee', '1420 S Congress Ave, Austin, TX 78704', 'Austin', 'TX', 'USA', 30.2489, -97.7501, 'A sunlit corner room on South Congress where the light does half the work. Slow mornings, single-origin pour-overs, and a pastry case that empties by ten.', 'https://morninghouse.coffee', '@morninghousecoffee', '(512) 555-0142', 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80', array['https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80']::text[], true, 'approved', 'South Congress', 'Honey Oat Cortado', 'Mon–Sun 7:00–18:00', 4.8, 214, 2),
  ('Eastside Roasters', '2210 E 6th St, Austin, TX 78702', 'Austin', 'TX', 'USA', 30.2617, -97.7215, 'A working roastery with a cupping table open to anyone curious. The espresso rotates weekly and the baristas will happily talk you through the roast.', 'https://eastsideroasters.co', '@eastsideroasters', '(512) 555-0177', 'https://images.unsplash.com/photo-1442550528053-c431ecb55509?auto=format&fit=crop&w=1200&q=80', array['https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1459755486867-b55449bb39ff?auto=format&fit=crop&w=1200&q=80']::text[], true, 'approved', 'East Austin', 'Rotating Single-Origin Espresso', 'Mon–Sun 7:00–18:00', 4.7, 189, 2),
  ('Paper Cup Café', '4302 Ave G, Austin, TX 78751', 'Austin', 'TX', 'USA', 30.3049, -97.7281, 'A tiny neighborhood favorite tucked into a Hyde Park bungalow. Mismatched chairs, zines by the register, and a flat white worth the wait.', null, '@papercupatx', '(512) 555-0198', 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?auto=format&fit=crop&w=1200&q=80', array['https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=1200&q=80']::text[], false, 'approved', 'Hyde Park', 'Cardamom Flat White', 'Mon–Sun 7:00–18:00', 4.6, 96, 1),
  ('Green Room Coffee', '1201 W Lynn St, Austin, TX 78703', 'Austin', 'TX', 'USA', 30.2791, -97.7593, 'Ferns everywhere, filtered light, and a hush that makes it the unofficial study hall of Clarksville. Order the matcha; stay for the calm.', 'https://greenroom.coffee', '@greenroomatx', '(512) 555-0110', 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1200&q=80', array['https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=1200&q=80']::text[], true, 'approved', 'Clarksville', 'Ceremonial Matcha Latte', 'Mon–Sun 7:00–18:00', 4.7, 152, 2),
  ('Ember & Oak Coffee', '86 Rainey St, Austin, TX 78701', 'Austin', 'TX', 'USA', 30.2589, -97.7385, 'Coffee by day, coffee cocktails by night. Reclaimed oak, low amber light, and an espresso martini that has ruined other espresso martinis for us.', 'https://emberoak.bar', '@emberoakatx', '(512) 555-0163', 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=1200&q=80', array['https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1514066558159-fc8c737ef259?auto=format&fit=crop&w=1200&q=80']::text[], false, 'approved', 'Rainey Street', 'Oak-Smoked Espresso Martini', 'Mon–Sun 7:00–00:00', 4.5, 174, 3),
  ('South Congress Espresso', '1600 S Congress Ave, Austin, TX 78704', 'Austin', 'TX', 'USA', 30.2470, -97.7503, 'A slim espresso bar built for the perfect shot and a quick hello. No laptops, no fuss — just some of the most dialed-in espresso in the city.', null, '@scespresso', '(512) 555-0125', 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?auto=format&fit=crop&w=1200&q=80', array['https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80']::text[], true, 'approved', 'South Congress', 'Piccolo Latte', 'Mon–Sun 7:00–18:00', 4.9, 241, 2),
  ('Juniper Coffee Bar', '1911 Aldrich St, Austin, TX 78723', 'Austin', 'TX', 'USA', 30.2994, -97.7052, 'Airy and family-friendly on the Mueller lawn, with a big patio, house-made horchata cold brew, and enough outlets to survive a work sprint.', 'https://junipercoffee.bar', '@juniperatx', '(512) 555-0189', 'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=1200&q=80', array['https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1200&q=80']::text[], false, 'approved', 'Mueller', 'Horchata Cold Brew', 'Mon–Sun 7:00–18:00', 4.6, 118, 2)
),
ins as (
  insert into public.cafes (name, address, city, state, country, latitude, longitude, description, website, instagram, phone, cover_photo_url, gallery, verified_by_joe, status, neighborhood, signature_drink, hours, rating, review_count, price_tier)
  select name, address, city, state, country, latitude, longitude, description, website, instagram, phone, cover_photo_url, gallery, verified_by_joe, status, neighborhood, signature_drink, hours, rating, review_count, price_tier from seeded
  returning id, name
)
insert into public.cafe_tags (cafe_id, category, tag)
select ins.id, v.category, v.tag from ins
join (values
    ('Morning House Coffee', 'Atmosphere & Design', 'Bright & Airy'),
    ('Morning House Coffee', 'Atmosphere & Design', 'Plant-Filled'),
    ('Morning House Coffee', 'Atmosphere & Design', 'Cozy'),
    ('Morning House Coffee', 'Amenities', 'Wi-Fi'),
    ('Morning House Coffee', 'Amenities', 'Outlets'),
    ('Morning House Coffee', 'Amenities', 'Outdoor Seating'),
    ('Morning House Coffee', 'Food & Beverage Focus', 'Single Origin'),
    ('Morning House Coffee', 'Food & Beverage Focus', 'House-Made Syrups'),
    ('Morning House Coffee', 'Food & Beverage Focus', 'Breakfast Menu'),
    ('Morning House Coffee', 'Soundscape', 'Conversational'),
    ('Morning House Coffee', 'Soundscape', 'Background Music'),
    ('Morning House Coffee', 'Dietary & Allergy Friendly', 'Vegan Friendly'),
    ('Morning House Coffee', 'Dietary & Allergy Friendly', 'Gluten-Free Options'),
    ('Morning House Coffee', 'Type of Establishment', 'Brick & Mortar Café'),
    ('Eastside Roasters', 'Atmosphere & Design', 'Industrial'),
    ('Eastside Roasters', 'Atmosphere & Design', 'Minimalist'),
    ('Eastside Roasters', 'Amenities', 'Wi-Fi'),
    ('Eastside Roasters', 'Amenities', 'Parking'),
    ('Eastside Roasters', 'Amenities', 'Wheelchair Accessible'),
    ('Eastside Roasters', 'Food & Beverage Focus', 'Third Wave Coffee'),
    ('Eastside Roasters', 'Food & Beverage Focus', 'Single Origin'),
    ('Eastside Roasters', 'Food & Beverage Focus', 'Multi-Roaster Program'),
    ('Eastside Roasters', 'Soundscape', 'Lively'),
    ('Eastside Roasters', 'Soundscape', 'Vinyl Listening'),
    ('Eastside Roasters', 'Community', 'Workshops'),
    ('Eastside Roasters', 'Community', 'Events'),
    ('Eastside Roasters', 'Type of Establishment', 'Roastery'),
    ('Eastside Roasters', 'Type of Establishment', 'Brick & Mortar Café'),
    ('Paper Cup Café', 'Atmosphere & Design', 'Cozy'),
    ('Paper Cup Café', 'Atmosphere & Design', 'Vintage'),
    ('Paper Cup Café', 'Atmosphere & Design', 'Artsy'),
    ('Paper Cup Café', 'Amenities', 'Wi-Fi'),
    ('Paper Cup Café', 'Amenities', 'Outlets'),
    ('Paper Cup Café', 'Amenities', 'Pet Friendly'),
    ('Paper Cup Café', 'Food & Beverage Focus', 'House-Made Syrups'),
    ('Paper Cup Café', 'Food & Beverage Focus', 'Breakfast Menu'),
    ('Paper Cup Café', 'Soundscape', 'Quiet'),
    ('Paper Cup Café', 'Community', 'Local Art'),
    ('Paper Cup Café', 'Community', 'Book Clubs'),
    ('Paper Cup Café', 'Dietary & Allergy Friendly', 'Vegetarian Friendly'),
    ('Paper Cup Café', 'Dietary & Allergy Friendly', 'Dairy-Free Options'),
    ('Paper Cup Café', 'Type of Establishment', 'Brick & Mortar Café'),
    ('Green Room Coffee', 'Atmosphere & Design', 'Plant-Filled'),
    ('Green Room Coffee', 'Atmosphere & Design', 'Bright & Airy'),
    ('Green Room Coffee', 'Atmosphere & Design', 'Minimalist'),
    ('Green Room Coffee', 'Amenities', 'Wi-Fi'),
    ('Green Room Coffee', 'Amenities', 'Outlets'),
    ('Green Room Coffee', 'Amenities', 'Restrooms'),
    ('Green Room Coffee', 'Amenities', 'Wheelchair Accessible'),
    ('Green Room Coffee', 'Food & Beverage Focus', 'Single Origin'),
    ('Green Room Coffee', 'Food & Beverage Focus', 'House-Made Syrups'),
    ('Green Room Coffee', 'Soundscape', 'Quiet'),
    ('Green Room Coffee', 'Soundscape', 'Background Music'),
    ('Green Room Coffee', 'Dietary & Allergy Friendly', 'Vegan Friendly'),
    ('Green Room Coffee', 'Dietary & Allergy Friendly', 'Gluten-Free Options'),
    ('Green Room Coffee', 'Dietary & Allergy Friendly', 'Nut-Free Options'),
    ('Green Room Coffee', 'Type of Establishment', 'Brick & Mortar Café'),
    ('Ember & Oak Coffee', 'Atmosphere & Design', 'Rustic'),
    ('Ember & Oak Coffee', 'Atmosphere & Design', 'Industrial'),
    ('Ember & Oak Coffee', 'Atmosphere & Design', 'Elegant'),
    ('Ember & Oak Coffee', 'Amenities', 'Wi-Fi'),
    ('Ember & Oak Coffee', 'Amenities', 'Outdoor Seating'),
    ('Ember & Oak Coffee', 'Amenities', 'Parking'),
    ('Ember & Oak Coffee', 'Food & Beverage Focus', 'Coffee Cocktails'),
    ('Ember & Oak Coffee', 'Food & Beverage Focus', 'Alcohol Served'),
    ('Ember & Oak Coffee', 'Food & Beverage Focus', 'Dinner Menu'),
    ('Ember & Oak Coffee', 'Soundscape', 'Lively'),
    ('Ember & Oak Coffee', 'Soundscape', 'Live Music'),
    ('Ember & Oak Coffee', 'Soundscape', 'DJ Sets'),
    ('Ember & Oak Coffee', 'Community', 'Events'),
    ('Ember & Oak Coffee', 'Community', 'Open Mic'),
    ('Ember & Oak Coffee', 'Type of Establishment', 'Café & Bar'),
    ('South Congress Espresso', 'Atmosphere & Design', 'Minimalist'),
    ('South Congress Espresso', 'Atmosphere & Design', 'Mid-Century Modern'),
    ('South Congress Espresso', 'Amenities', 'Outdoor Seating'),
    ('South Congress Espresso', 'Food & Beverage Focus', 'Third Wave Coffee'),
    ('South Congress Espresso', 'Food & Beverage Focus', 'Single Origin'),
    ('South Congress Espresso', 'Soundscape', 'Conversational'),
    ('South Congress Espresso', 'Dietary & Allergy Friendly', 'Dairy-Free Options'),
    ('South Congress Espresso', 'Type of Establishment', 'Coffee Stand'),
    ('Juniper Coffee Bar', 'Atmosphere & Design', 'Bright & Airy'),
    ('Juniper Coffee Bar', 'Atmosphere & Design', 'Cozy'),
    ('Juniper Coffee Bar', 'Amenities', 'Wi-Fi'),
    ('Juniper Coffee Bar', 'Amenities', 'Outlets'),
    ('Juniper Coffee Bar', 'Amenities', 'Outdoor Seating'),
    ('Juniper Coffee Bar', 'Amenities', 'Parking'),
    ('Juniper Coffee Bar', 'Amenities', 'EV Charging'),
    ('Juniper Coffee Bar', 'Amenities', 'Pet Friendly'),
    ('Juniper Coffee Bar', 'Food & Beverage Focus', 'House-Made Syrups'),
    ('Juniper Coffee Bar', 'Food & Beverage Focus', 'Breakfast Menu'),
    ('Juniper Coffee Bar', 'Food & Beverage Focus', 'Lunch Menu'),
    ('Juniper Coffee Bar', 'Soundscape', 'Conversational'),
    ('Juniper Coffee Bar', 'Soundscape', 'Background Music'),
    ('Juniper Coffee Bar', 'Community', 'Community Gatherings'),
    ('Juniper Coffee Bar', 'Community', 'Events'),
    ('Juniper Coffee Bar', 'Dietary & Allergy Friendly', 'Vegan Friendly'),
    ('Juniper Coffee Bar', 'Dietary & Allergy Friendly', 'Vegetarian Friendly'),
    ('Juniper Coffee Bar', 'Dietary & Allergy Friendly', 'Celiac Friendly'),
    ('Juniper Coffee Bar', 'Type of Establishment', 'Brick & Mortar Café')
) as v(name, category, tag) on v.name = ins.name;

commit;
